#!/usr/bin/env bash
# build.sh — build the Docker-only cac wrapper
set -euo pipefail

PROJ_DIR="$(cd "$(dirname "$0")" && pwd)"
SRC_DIR="$PROJ_DIR/src"
OUT="$PROJ_DIR/cac"

SOURCES=(
    utils.sh
    cmd_self.sh
    cmd_docker_common.sh
    cmd_docker_runtime.sh
    cmd_docker_ports.sh
    cmd_docker.sh
    cmd_version.sh
    cmd_help.sh
    main.sh
)

{
    echo '#!/usr/bin/env bash'
    echo '# cac-docker-claude — Docker-only Claude Code runtime'
    echo '# Generated by build.sh from src/. Do not edit this file directly.'
    echo 'set -euo pipefail'
    echo
    echo 'CAC_DIR="$HOME/.cac"'
    echo 'ENVS_DIR="$CAC_DIR/envs"'
    echo 'VERSIONS_DIR="$CAC_DIR/versions"'
    echo

    for file in "${SOURCES[@]}"; do
        src="$SRC_DIR/$file"
        if [[ ! -f "$src" ]]; then
            echo "error: missing $src" >&2; exit 1
        fi
        # 仅跳过源文件自身首行 shebang（保留 heredoc 内的 shebang）
        echo "# ━━━ $file ━━━"
        awk 'NR==1 && /^#!\// {next} {print}' "$src"
        echo
    done
} > "$OUT"

chmod +x "$OUT"

echo "✓ built → ${OUT} ($(wc -l < "${OUT}") lines)"
